version: "2"
services:
  mariadb:
    image: mariadb
    hostname: mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=root`
      - "MYSQL_ROOT_HOST=%"
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
